name: Run RC Validation
on:
  workflow_dispatch:
    
jobs:
  run_rc_validation:
    runs-on: [self-hosted,ubuntu-20.04]
    steps:
    - name: Set RELEASE_BRANCH env variable
      run: |
        RELEASE_BRANCH=release-${{env.RELEASE_VER}}
        echo "RELEASE_BRANCH=${RELEASE_BRANCH}" >> $GITHUB_ENV