name: Run RC Validation
on:
  workflow_dispatch:
    inputs:
      RELEASE_VER:
        description: Beam version of current release
        required: true
        default: vtest # remove default before merging
      USER_GCS_BUCKET:
        description: Bucket to upload results
        required: false
        default: none
      RC_NUM:
        description: RC number
        required: true
        default: none
jobs:
  run_rc_validation:
    runs-on: [self-hosted,ubuntu-20.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Common tasks
      uses: ./.github/actions/common-rc
    - name: Source Variables from file
      run: >
        cat dummyVars.config >> $GITHUB_ENV
    - name: Verifying source results
      run: echo $dummyValue
    - name: Verify ENV values
      run: |
        echo ""
        echo "====================Checking Environment & Variables================="
        echo "PLEASE update RC_VALIDATE_CONFIGS in file script.config first."
        echo ""
        echo "running validations on release ${RELEASE_VER} RC${RC_NUM}."
        echo "repo URL for this RC: ${REPO_URL}"
        echo "using workspace: ${LOCAL_BEAM_DIR}"
        echo "validate Python versions: "$(IFS=$' '; echo "${PYTHON_VERSIONS_TO_VALIDATE[*]}")
        echo ""