name: Run RC Validation
on:
  workflow_dispatch:
jobs:
  run_rc_validation:
    runs-on: [self-hosted,ubuntu-20.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Common tasks
      uses: ./.github/actions/setup-rc-vars
    - name: Source Variables from file
      run: >
        cat dummyVars.config >> $GITHUB_ENV
    - name: Verifying source results
      run: echo $dummyValue
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
    - name: Install hub
      run: sudo apt install -y hub
    - name: Set RELEASE_BRANCH env variable
      run: |
        RC_TAG="v${RELEASE_VER}-RC${RC_NUM}"
        RELEASE_BRANCH="releasev${RELEASE_VER}"
        WORKING_BRANCH=v${RELEASE_VER}-RC${RC_NUM}_validations
        GIT_REPO_URL=https://github.com/apache/beam.git
        PYTHON_RC_DOWNLOAD_URL=https://dist.apache.org/repos/dist/dev/beam
        HUB_VERSION=2.12.0
        HUB_ARTIFACTS_NAME=hub-linux-amd64-${HUB_VERSION}
        BACKUP_BASHRC=.bashrc_backup_$(date +"%Y%m%d%H%M%S")
        BACKUP_M2=settings_backup_$(date +"%Y%m%d%H%M%S").xml
        declare -a PYTHON_VERSIONS_TO_VALIDATE=("python3.8")
    - name: Verify ENV values
      run: |
        echo ""
        echo "====================Checking Environment & Variables================="
        echo "PLEASE update RC_VALIDATE_CONFIGS in file script.config first."
        echo ""
        echo "running validations on release ${RELEASE_VER} RC${RC_NUM}."
        echo "repo URL for this RC: ${REPO_URL}"
        echo "using workspace: ${LOCAL_BEAM_DIR}"
        echo "validate Python versions: "$(IFS=$' '; echo "${PYTHON_VERSIONS_TO_VALIDATE[*]}")
        echo ""