name: Run RC Validation
on:
  workflow_dispatch:
jobs:
  run_rc_validation:
    runs-on: [self-hosted,ubuntu-20.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Source Variables from file
      run: >
        set -a 
        . ./dummyVars.config
        set +a
        echo $dummyValue
    - name: Verifying source results
      run: echo $dummyValue
    - name: Set RELEASE_BRANCH env variable
      run: >
        RC_TAG="v${RELEASE_VER}-RC${RC_NUM}"
        RELEASE_BRANCH="releasev${RELEASE_VER}"
        WORKING_BRANCH=v${RELEASE_VER}-RC${RC_NUM}_validations
        GIT_REPO_URL=https://github.com/apache/beam.git
        PYTHON_RC_DOWNLOAD_URL=https://dist.apache.org/repos/dist/dev/beam
        HUB_VERSION=2.12.0
        HUB_ARTIFACTS_NAME=hub-linux-amd64-${HUB_VERSION}
        BACKUP_BASHRC=.bashrc_backup_$(date +"%Y%m%d%H%M%S")
        BACKUP_M2=settings_backup_$(date +"%Y%m%d%H%M%S").xml
        declare -a PYTHON_VERSIONS_TO_VALIDATE=("python3.8")