name: Python Leaderboard and GameStates
on:
  workflow_dispatch:
    inputs:
      RELEASE_VER:
        description: Beam version of current release
        required: true
        default: 2.42.0 # remove default before merging
      USER_GCS_BUCKET:
        description: Bucket to upload results
        required: false
        default: gs://rc-validation-migration-tests
      RC_NUM:
        description: RC number
        required: true
        default: "1"
env: # This should be a set of github secrets    
  USER_GCP_PROJECT: apache-beam-testing
  USER_GCP_REGION: us-central1
  USER_GCP_ZONE: us-central1-a
  REPO_URL: https://repository.apache.org/content/repositories/orgapachebeam-1284
jobs:
  python_cross_validation:
    runs-on: [self-hosted,ubuntu-20.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Common tasks
      uses: ./.github/actions/common-rc-validation
    - name: Verify ENV values
      run: |
        echo ""
        echo "====================Checking Environment & Variables================="
        echo ""
        echo "running validations on release ${{github.event.inputs.RELEASE_VER}} RC${{github.event.inputs.RC_NUM}}."
        echo "repo URL for this RC: $GIT_REPO_URL"
    - name: Install Kubectl 
      uses: azure/setup-kubectl@v3

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.2.1
      with:
        java-version: 11

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies
    - name: Downloading Python Staging RC
      run: |
        echo ""
        echo "====================Starting Python Cross-language Validations==============="
  

        echo "---------------------Downloading Python Staging RC----------------------------"
        wget ${PYTHON_RC_DOWNLOAD_URL}/${RELEASE_VER}/python/apache-beam-${RELEASE_VER}.zip
        wget ${PYTHON_RC_DOWNLOAD_URL}/${RELEASE_VER}/python/apache-beam-${RELEASE_VER}.zip.sha512
        if [[ ! -f apache-beam-$RELEASE_VER.zip ]]; then
          { echo "Fail to download Python Staging RC files." ;exit 1; }
        fi

        echo "--------------------------Verifying Hashes------------------------------------"
        sha512sum -c apache-beam-${RELEASE_VER}.zip.sha512

        `which pip` install --upgrade pip
        `which pip` install --upgrade setuptools

        KAFKA_CLUSTER_NAME=xlang-kafka-cluster-$RANDOM
    - name: Installing gcloud-auth-plugin
      run: sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
    - name: Setting Kafka Cluster Name # TODO: change to random again once the tests are finished
      run: |
        echo "KAFKA_CLUSTER_NAME=xlang-kafka-cluster-12817">> $GITHUB_ENV 
#    - name: Creating Kafka Cluster
#      run: |
#        gcloud container clusters create --project=${USER_GCP_PROJECT} --region=${USER_GCP_REGION} --no-enable-ip-alias $KAFKA_CLUSTER_NAME
#        kubectl apply -R -f .test-infra/kubernetes/kafka-cluster
#    - name: Getting cluster credentials
#      run: gcloud container clusters get-credentials ${KAFKA_CLUSTER_NAME} --region ${USER_GCP_REGION} --project ${USER_GCP_PROJECT}
    - name: Setting Python Environment
      run: |
        echo "--------------------------Installing Python SDK-------------------------------"
        pip install --upgrade pip setuptools wheel
        pip install apache-beam-${RELEASE_VER}.zip[gcp]
#    - name: Waiting for Kafka cluster to be ready
#      run: kubectl wait --for=condition=Ready pod/kafka-0 --timeout=900s
    - name: Donwloading Python RC
      run: |
        echo "---------------------Downloading Python Staging RC----------------------------"
        wget ${PYTHON_RC_DOWNLOAD_URL}/${RELEASE_VER}/python/apache-beam-${RELEASE_VER}.zip
        wget ${PYTHON_RC_DOWNLOAD_URL}/${RELEASE_VER}/python/apache-beam-${RELEASE_VER}.zip.sha512
    - name: Verifying Hashes
      run: |
        echo "--------------------------Verifying Hashes------------------------------------"
        sha512sum -c apache-beam-${RELEASE_VER}.zip.sha512
    - name: Updating Settings
      run: |
        mkdir .m2
        cd .m2
        touch settings.xml
        echo "<settings>" >> settings.xml
        echo "  <profiles>" >> settings.xml
        echo "    <profile>" >> settings.xml
        echo "      <id>release-repo</id>" >> settings.xml
        echo "      <activation>" >> settings.xml
        echo "        <activeByDefault>true</activeByDefault>" >> settings.xml
        echo "      </activation>" >> settings.xml
        echo "      <repositories>" >> settings.xml
        echo "        <repository>" >> settings.xml
        echo "          <id>Release ${RELEASE_VER} RC${{github.event.inputs.RC_NUM}}</id>" >> settings.xml
        echo "          <name>Release ${RELEASE_VER} RC${{github.event.inputs.RC_NUM}}</name>" >> settings.xml
        echo "          <url>${REPO_URL}</url>" >> settings.xml
        echo "        </repository>" >> settings.xml
        echo "      </repositories>" >> settings.xml
        echo "    </profile>" >> settings.xml
        echo "  </profiles>" >> settings.xml
        echo "</settings>" >> settings.xml
        cat settings.xml
    - name: Generate Maven archetype
      run: |
        mvn archetype:generate \
        -DarchetypeGroupId=org.apache.beam \
        -DarchetypeArtifactId=beam-sdks-java-maven-archetypes-examples \
        -DarchetypeVersion=${RELEASE_VER} \
        -DgroupId=org.example \
        -DartifactId=word-count-beam \
        -Dversion="0.1" \
        -Dpackage=org.apache.beam.examples \
        -DinteractiveMode=false \
        -DarchetypeCatalog=internal